version: '3.8'

services:
  backend:
    build: 
      context: .
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - .:/app
  
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 33060:3306

volumes:
  dbdata:
